### ISSUE TITLE
Add ical

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-vocabularies#18]
Via @iherman I got links to the following RDF resources, taken from his mail:

- [x] `as`: https://www.w3.org/ns/activitystreams-owl.ttl
- [x] `ical`: http://www.w3.org/2002/12/cal/icaltzd.rdf  (it downloads the RDF/XML file in most browsers instead of displaying it)
- [x] `xhv`: http://tinyurl.com/yy4pbocc (the vocabulary is in the HTML file in RDFa, and this URL runs the RDFa distiller to return the turtle file)

Those should be sourced as well

**Comment by vhf** [comment]
`as` and `xhv`: all good!

`ical` makes https://github.com/rdfjs/rdfxml-streaming-parser.js crash with:

> Found multiple occurrences of rdf:ID='http://www.w3.org/2002/12/cal/icaltzd#standard'.

**Comment by iherman** [comment]
@vhf I cannot comment on the streaming parser code. If I do

```
curl http://www.w3.org/2002/12/cal/icaltzd#standard
```

it works and returns an RDF/XML code.

**Comment by vhf** [comment]
@iherman Thanks, yes this serves `Content-Location: icaltzd.rdf` (`curl -I http://www.w3.org/2002/12/cal/icaltzd#standard`). 

The issue is that this file cannot be parsed, it is probably not valid according to the schema. Here is the file, there might be other problems than these two but here's what the parser first notices:
https://gist.github.com/vhf/23705814109f8c18cfb100c053f3dc6b#file-icaltzd-rdf-L705-L722
These two are repeated 3 times:

```xml
  <owl:ObjectProperty rdf:ID="standard">
    <rdfs:label>STANDARD</rdfs:label>
  </owl:ObjectProperty>
  <owl:ObjectProperty rdf:ID="daylight">
    <rdfs:label>DAYLIGHT</rdfs:label>
  </owl:ObjectProperty>
```

**Comment by ktk** [comment]
I tried with `rapper` and `riot` as well, both with proper RDF/XML support. Neither of it is parsing the file. I will see if we can manually fix it, in that form it indeed does not seem to be valid.

**Comment by iherman** [comment]
Hm. I agree it is ugly. But I am not sure it is a bug. `rdf:ID` does not have to be unique in the sense like, for example `xml:id` must be: it is only an abbreviation of a URL. I.e., I wonder whether it is not the parser that is over-eager.

**Comment by ktk** [comment]
Hmm indeed, in `riot` it's just warnings, not errors. I will report this to the RDF/XML parser.

**Comment by tpluscode** [comment]
One would need to check with the spec. But, FWIW, it also fails on rdf-translator.appspot.com (Ruby RDFlib) as well as dotNetRDF :)

**Comment by iherman** [comment]
Per [RDF/XML spec](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-ID-xml-base):

> The `rdf:ID` attribute on a node element (not property element, that has another meaning) can be used instead of `rdf:about` and gives a relative IRI equivalent to # concatenated with the `rdf:ID` attribute value. 

I.e., just as it is possible to repeat the value of `rdf:about` (it is "just" a URI) it is also possible to repeat `rdf:ID`.

In other words, and in spite of its name, `rdf:ID` is _not_ the same as `xml:id` (or the `id` attribute in HTML) which assigns a unique ID to an element in the XML/HTML tree.

**Comment by rubensworks** [comment]
This is also mentioned in the [spec](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-ID-xml-base):

> `rdf:ID` provides an additional check since the same name can only appear once in the scope of an `xml:base` value (or document, if none is given), so is useful for defining a set of distinct, related terms relative to the same IRI.

If I understand this part correctly, then the parsers that error on this document behave correctly.

In any case, I don't see a good reason to force a crash on this, which is why I'll add [a config option to the streaming parser to disable this strict behaviour](https://github.com/rdfjs/rdfxml-streaming-parser.js/issues/18#issuecomment-508036704).

**Comment by iherman** [comment]
To be honest, I am not sure I fully understand that sentence... And it is in contradiction with what precedes, which says that `rdf:ID` is some sort of an abbreviation of `rdf:about`. Clearly, `rdf:about` can appear in the same RDF document many times...

I think it is certainly a good idea not to consider this as a full error and issue a warning instead.

(I wonder whether it is not a good idea to submit an official errata for RDF 1.1 on that.)

**Comment by danbri** [comment]
It is certainly confusing and to some extent misleading, but I wouldn't say they directly contradict each other. 

If you get past "rdf:ID provides an additional check since the same name can only appear once in the scope of an xml:base value (or document, if none is given), so is useful for defining a set of distinct, related terms relative to the same IRI." ... then yes, it "can be used instead of rdf:about and gives a relative IRI equivalent to # concatenated with the rdf:ID attribute value."

Definitely errata material, worth a quick email to www-rdf-comments@ if that's where the most recent specs request errata drafts...

**Comment by ktk** [comment]
@vhf there is now an option in the RDF/XML parser, see linked issue from Ruben

**Comment by vhf** [comment]
Great, it worked nicely, thanks @rubensworks !
