### ISSUE TITLE
submit QUDT to LOV

### ISSUE THREAD

**Issue by VladimirAlexiev** [zazuko/rdf-vocabularies#24]
QUDT is missing from LOV: https://lov.linkeddata.es/dataset/lov/terms?q=qudt. If as part of #13 you dig through the structure of QUDT, it would be great if you submit it properly to LOV.

**Comment by ktk** [comment]
It looks like the submit form is [this one](https://lov.linkeddata.es/dataset/lov/suggest) and the only thing one can add is a namespace IRI so my guess is they noticed, as we did, that sourcing is not that easy. Best would be if they source our file but no idea who does that work to point them to it.

**Comment by VladimirAlexiev** [comment]
That's @pyvandenbussche, @mariapoveda and ghislain.atemezing AT gmail (can't find his handle)

**Comment by mariapoveda** [comment]
@ktk Could you tell me which IRI did you suggested? I can't find qudt in the suggestions list

**Comment by ktk** [comment]
@mariapoveda will finally be done now, see #13. The list we plan to source:

* http://qudt.org/schema/qudt/
* http://qudt.org/schema/datatype.ttl
* http://qudt.org/vocab/constant/
* http://qudt.org/vocab/discipline/
* http://qudt.org/vocab/prefix/
* http://qudt.org/vocab/dimensionvector/
* http://qudt.org/vocab/quantitykind/
* http://qudt.org/vocab/sou/

**Comment by mariapoveda** [comment]
Great. Do you plan to suggest all the URIs? Remember each ontology should include the metadata listed at https://lov.linkeddata.es/Recommendations_Vocabulary_Design.pdf

**Comment by steveraysteveray** [comment]
Hi all,
I had previously already submitted the QUDT schema to LOV, [here](https://lov.linkeddata.es/dataset/lov/vocabs/qudt). I was a little surprised in the recommendations mentioned by @mariapoveda above that states "Few instances except for examples". Unlike the recommendation, we distinguish the ontology (the QUDT schema graph) from the vocabularies (the units, quantitykinds, etc.). That's why you see the folder structure showing ../schema/.. and ../vocab/..

So I never submitted any of what we call the QUDT vocabularies to LOV, because they are all instances.

**Comment by ktk** [comment]
Did what I could ;) closing here.
