### ISSUE TITLE
Extract prefix list into its own library

### ISSUE THREAD

**Issue by thewilkybarkid** [zazuko/rdf-vocabularies#55]
`@zazuko/rdf-vocabularies` is quite large (nearly 20MB). https://github.com/tpluscode/rdf-ns-builders/commit/3019d712728641b7136a16726a8afa276e6a4868 was committed to avoid forcing this as a runtime dependency, but there are still cases where it would be useful to have a simple library containing just [prefixes.js](https://github.com/zazuko/rdf-vocabularies/blob/master/src/lib/prefixes.ts) to avoid having to hard-code the IRIs elsewhere (eg https://github.com/libero/article-store/pull/260#discussion_r386256372).

Would it be possible to extract this into its own package? (`@zazuko/rdf-vocabulary-prefixes` or something?)

**Comment by ktk** [comment]
Good point, I think it makes sense to reflect what we were trying to do and what we might want to do in the future and then decide what should be done next.

My initial goal in another repo was to have predefined prefixes that I could use anywhere, a bit like a pre-configured [namespaces](https://github.com/rdfjs-base/namespace) that would be used within the code but also when I for example serialize to Turtle or do something with JSON-LD. When we started working on that we started to source ontologies, which was more difficult than it should be so we thought it makes sense to store them as well so we don't have to go through that pain every time we need classes/properties of vocabularies.

After that we created [prefix.zazuko.com](https://prefix.zazuko.com/) because that made sense with what we had as a base. Later we added some APIs to the prefix service so we can use that from tools that need autocomplete.

So my current list of things that would be useful are

- prefixes, without content (classes/properties/...). For those who agree with us that this is a good collection of common prefixes
- the whole schema/ontology in RDF for those who do not use JS but do not want to go through the same pain we did for fetching them. They might probably cherrypick the ones they need
- the whole schema/ontology in a form that JS libs can use it without the need to parse it first, so in some form of JS structures.

We used it in various ways, I fetched a list of classes/properties for certain prefixes via the API provided by prefix.zazuko.com but some colleagues used it differently.

So @bergos @tpluscode @martinmaillard @vhf @l00mi @mchlrch any comments here?

**Comment by tpluscode** [comment]
> My initial goal in another repo was to have predefined prefixes that I could use anywhere, a bit like a pre-configured namespaces

> prefixes, without content

Cue [@tpluscode/rdf-ns-builders](https://github.com/tpluscode/rdf-ns-builders) which @thewilkybarkid mentions above.

You gave me an idea to maybe also generate exports of only property name and only class names, etc.

> the whole schema/ontology in RDF

I believe that rdf-vocabularies provides this feature nicely?

> the whole schema/ontology in a form that JS libs can use it without the need to parse it first

this might be useful in browser environment if it can make do without importing the large-ish RDF/JS dependencies

**Comment by vhf** [comment]
> there are still cases where it would be useful to have a simple library containing just [prefixes.js](https://github.com/zazuko/rdf-vocabularies/blob/master/src/lib/prefixes.ts) to avoid having to hard-code the IRIs elsewhere (eg https://github.com/libero/article-store/pull/260#discussion_r386256372).
> 
> Would it be possible to extract this into its own package? (`@zazuko/rdf-vocabulary-prefixes` or something?)

I like this idea, it looks clean and simple.

**Comment by ktk** [comment]
@tpluscode yes it does, I just want to list all possible use-cases I could think of

**Comment by tpluscode** [comment]
I just got this idea to extract the code used to generate this package contents (index, etc.) as well as the generator of `@tpluscode/rdf-ns-builders` 

This would allow others to create their own similar packages for other ontologies which we might not want to incorporate in this list for some reason.

**Comment by tpluscode** [comment]
@thewilkybarkid coming back to this, is the problem the total size of this package? Granted, it is bound to grow until we break it up into smaller pieces (if ever) but at runtime your application would not be affected thanks to tree shaking and dynamic imports.

You can `import { prefixes } from '@zazuko/rdf-vocabularies` or even `import prefixes from '@zazuko/rdf-vocabularies/prefixes'` and you will get a plain JS object with all namespaces

Is this good enough to close?

**Comment by thewilkybarkid** [comment]
Yeah, it was about NPM usage rather than runtime. This is made worse when using Docker, though BuildKit helps locally as you can now mount in a cache during the build (but not in CI).

**Comment by tpluscode** [comment]
Ok, here's another idea. 

@ktk how about a `@zazuko/rdf-vocabularies-lite` package which would be exactly the same thing minus the actual datasets? We could have it deployed automatically to match version

**Comment by ktk** [comment]
I think we should reflect how we use it right now and how we might use it in the future. Not a problem for me to split things but I would do it in a way that it stays like this for a while.

Right now is very JS centric but the content/ontologies are useful in many other contexts as well.

**Comment by tpluscode** [comment]
We recently looked at some docker image of our apps. We managed to get it down to ~350 MB where 80 MB was the vocabularies package

I think it does justify the need to separate the actual datasets.
